//loaders
//login loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
//leads loaders
export const LEADS_FETCH_ENABLE_LOADER = 'LEADS_FETCH_ENABLE_LOADER';
export const LEADS_FETCH_DISABLE_LOADER = 'LEADS_FETCH_DISABLE_LOADER';
export const LEADS_FETCH_SINGLE_ENABLE_LOADER =
  'LEADS_FETCH_SINGLE_ENABLE_LOADER';
export const LEADS_FETCH_SINGLE_DISABLE_LOADER =
  'LEADS_FETCH_SINGLE_DISABLE_LOADER';
//oppotunities loaders
export const OPPORTUNITIES_FETCH_ENABLE_LOADER =
  'OPPORTUNITIES_FETCH_ENABLE_LOADER';
export const OPPORTUNITIES_FETCH_DISABLE_LOADER =
  'OPPORTUNITIES_FETCH_DISABLE_LOADER';
export const OPPORTUNITY_FETCH_SINGLE_ENABLE_LOADER =
  'OPPORTUNITY_FETCH_SINGLE_ENABLE_LOADER';
export const OPPORTUNITY_FETCH_SINGLE_DISABLE_LOADER =
  'OPPORTUNITY_FETCH_SINGLE_DISABLE_LOADER';
//leads count loaders
export const LEADS_COUNT_ENABLE_LOADER = 'LEADS_COUNT_ENABLE_LOADER';
export const LEADS_COUNT_DISABLE_LOADER = 'LEADS_COUNT_DISABLE_LOADER';
//opportunites count loaders
export const OPPORTUNITIES_COUNT_ENABLE_LOADER =
  'OPPORTUNITIES_COUNT_ENABLE_LOADER';
export const OPPORTUNITIES_COUNT_DISABLE_LOADER =
  'OPPORTUNITIES_COUNT_DISABLE_LOADER';
//dashboard header loaders
export const DASHBOARD_HEADER_ENABLE_LOADER = 'DASHBOARD_HEADER_ENABLE_LOADER';
export const DASHBOARD_HEADER_DISABLE_LOADER =
  'DASHBOARD_HEADER_DISABLE_LOADER';
//dropdown loaders
export const LEADS_DROPDOWN_DISABLE_LOADER = 'LEADS_DROPDOWN_DISABLE_LOADER';
export const LEADS_DROPDOWN_ENABLE_LOADER = 'LEADS_DROPDOWN_ENABLE_LOADER';
//add leads loader
export const ADD_LEADS_DISABLE_LOADER = 'ADD_LEADS_DISABLE_LOADER';
export const ADD_LEADS_ENABLE_LOADER = 'ADD_LEADS_ENABLE_LOADER';
//change to customer and quotation
export const CHANGE_TO_CUSTOMER_DISABLE_LOADER =
  'CHANGE_TO_CUSTOMER_DISABLE_LOADER';
export const CHANGE_TO_CUSTOMER_ENABLE_LOADER =
  'CHANGE_TO_CUSTOMER_ENABLE_LOADER';
export const CHANGE_TO_QUOTATION_ENABLE_LOADER =
  'CHANGE_TO_QUOTATION_ENABLE_LOADER';
export const CHANGE_TO_QUOTATION_DISABLE_LOADER =
  'CHANGE_TO_QUOTATION_DISABLE_LOADER';
export const CHANGE_STATUS_ENABLE_LOADER = 'CHANGE_STATUS_ENABLE_LOADER';
export const CHANGE_STATUS_DISABLE_LOADER = 'CHANGE_STATUS_DISABLE_LOADER';

//theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';

//leads
export const LEADS_FETCH_REQUEST = 'LEADS_FETCH_REQUEST';
export const LEADS_FETCH_RESPONSE = 'LEADS_FETCH_RESPONSE';
export const LEADS_FETCH_FAILED = 'LEADS_FETCH_FAILED';
export const LEADS_FETCH_ERROR = 'LEADS_FETCH_ERROR';

//lead
export const LEADS_FETCH_SINGLE_REQUEST = 'LEADS_FETCH_SINGLE_REQUEST';
export const LEADS_FETCH_SINGLE_RESPONSE = 'LEADS_FETCH_SINGLE_RESPONSE';
export const LEADS_FETCH_SINGLE_FAILED = 'LEADS_FETCH_SINGLE_FAILED';
export const LEADS_FETCH_SINGLE_ERROR = 'LEADS_FETCH_SINGLE_ERROR';

//opportunities
export const FETCH_OPPORTUNITIES_REQUEST = 'FETCH_OPPORTUNITIES_REQUEST';
export const OPPORTUNITIES_FETCH_RESPONSE = 'OPPORTUNITIES_FETCH_RESPONSE';
export const OPPORTUNITIES_FETCH_FAILED = 'OPPORTUNITIES_FETCH_FAILED';
export const OPPORTUNITIES_FETCH_ERROR = 'OPPORTUNITIES_FETCH_ERROR';

//opportunity
export const OPPORTUNITY_FETCH_SINGLE_REQUEST =
  'OPPORTUNITY_FETCH_SINGLE_REQUEST';
export const OPPORTUNITY_FETCH_SINGLE_RESPONSE =
  'OPPORTUNITY_FETCH_SINGLE_RESPONSE';
export const OPPORTUNITY_FETCH_SINGLE_FAILED =
  'OPPORTUNITY_FETCH_SINGLE_FAILED';
export const OPPORTUNITY_FETCH_SINGLE_ERROR = 'OPPORTUNITY_FETCH_SINGLE_ERROR';

//dashboard
//leadsCount
export const GET_LEADS_COUNT_REQUEST = 'GET_LEADS_COUNT_REQUEST';
export const GET_LEADS_COUNT_FAILED = 'GET_LEADS_COUNT_FAILED';
export const GET_LEADS_COUNT_RESPONSE = 'GET_LEADS_COUNT_RESPONSE';
export const GET_LEADS_COUNT_ERROR = 'GET_LEADS_COUNT_ERROR';
export const ADD_LEADS_COUNT = 'ADD_LEADS_COUNT';
export const SUBTRACT_LEADS_COUNT = 'SUBTRACT_LEADS_COUNT';
//opprtunities count
export const GET_OPPORTUNITIES_COUNT_REQUEST =
  'GET_OPPORTUNITIES_COUNT_REQUEST';
export const GET_OPPORTUNITIES_COUNT_FAILED = 'GET_OPPORTUNITIES_COUNT_FAILED';
export const GET_OPPORTUNITIES_COUNT_RESPONSE =
  'GET_OPPORTUNITIES_COUNT_RESPONSE';
export const GET_OPPORTUNITIES_COUNT_ERROR = 'GET_OPPORTUNITIES_COUNT_ERROR';
export const ADD_OPPORTUNITIES_COUNT = 'ADD_OPPORTUNITIES_COUNT';
export const SUBTRACT_OPPORTUNITIES_COUNT = 'SUBTRACT_OPPORTUNITIES_COUNT';
//dashboard header
export const GET_DASHBOARD_HEADER_REQUEST = 'GET_DASHBOARD_HEADER_REQUEST';
export const GET_DASHBOARD_HEADER_RESPONSE = 'GET_DASHBOARD_HEADER_RESPONSE';
export const GET_DASHBOARD_HEADER_ERROR = 'GET_DASHBOARD_HEADER_ERROR';

//leads dropdown
export const GET_LEADS_DROPDOWN_REQUEST = 'GET_LEADS_DROPDOWN_REQUEST';
export const GET_LEADS_DROPDOWN_RESPONSE = 'GET_LEADS_DROPDOWN_RESPONSE';
export const GET_LEADS_DROPDOWN_ERROR = 'GET_LEADS_DROPDOWN_ERROR';

//add leads
export const ADD_LEADS_REQUEST = 'ADD_LEADS_REQUEST';
export const ADD_LEADS_RESPONSE = 'ADD_LEADS_RESPONSE';
export const ADD_LEADS_FAILED = 'ADD_LEADS_FAILED';
export const ADD_LEADS_ERROR = 'ADD_LEADS_ERROR';
export const CLEAR_ADD_DATA = 'CLEAR_ADD_DATA';

//change customer and quotation
//customer
export const CHANGE_TO_CUSTOMER_REQUEST = 'CHANGE_TO_CUSTOMER_REQUEST';
export const CHANGE_TO_CUSTOMER_RESPONSE = 'CHANGE_TO_CUSTOMER_RESPONSE';
export const CHANGE_TO_CUSTOMER_ERROR = 'CHANGE_TO_CUSTOMER_ERROR';
export const CLEAR_CHANGE_TO_CUSTOMER_ERROR = 'CLEAR_CHANGE_TO_CUSTOMER_ERROR';
export const CLEAR_CHANGE_TO_CUSTOMER_SUCCESS =
  'CLEAR_CHANGE_TO_CUSTOMER_SUCCESS';
//quotation
export const CHANGE_TO_QUOTATION_REQUEST = 'CHANGE_TO_QUOTATION_REQUEST';
export const CHANGE_TO_QUOTATION_RESPONSE = 'CHANGE_TO_QUOTATION_RESPONSE';
export const CHANGE_TO_QUOTATION_ERROR = 'CHANGE_TO_QUOTATION_ERROR';

//change status
export const CHANGE_STATUS_REQUEST = 'CHANGE_STATUS_REQUEST';
export const CHANGE_STATUS_RESPONSE = 'CHANGE_STATUS_RESPONSE';
export const CHANGE_STATUS_ERROR = 'CHANGE_STATUS_ERROR';
